---
- name: Install chrome keys
  become: true
  apt_key:
    url: "{{ chrome_apt_keyurl }}"
    state: present

- name: Install chrome apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: "google-chrome"
    update_cache: yes
  register: chrome_install_packages
  with_items: '{{chrome_apt_repositories}}'

- name: Install chrome server apt packages
  become: true
  apt:
    pkg: '{{ item }}'
    state: present
    force: yes
  with_items: '{{chrome_apt_packages}}'
