---
- name: Install dependencies
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - build-essential
    - cmake
    - pkg-config
    - libc6-dev
    - g++-multilib
    - autoconf
    - libtool
    - unzip
    - git
    - automake
