---
- name: Install dependencies
  become: true
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - build-essential
    - cmake
    - pkg-config
    - autoconf
    - libtool
    - unzip
    - git
    - automake
    - tree
    - python-dev
    - python-pip
    - python3.4-dev
    - python3-pip
