---
- name: Install libraries for DIGITS
  become: true
  apt: name={{ item }} state=present install_recommends=no
  with_items:
  - graphviz
  - python-dev
  - python-flask
  - python-flaskext.wtf
  - python-gevent
  - python-h5py
  - python-numpy
  - python-pil
  - python-pip
  - python-protobuf
  - python-scipy
  - python-tk

- name: Check if temporary directory already exists
  stat: path={{ download_dir }}
  register: tmp

- name: Create temporary download directory
  file: name={{ download_dir }} state=directory
  when: tmp.stat.exists == false

- name: Download and unzip DIGITS
  unarchive: src=https://github.com/NVIDIA/DIGITS/archive/v{{ digits_version }}.tar.gz dest={{ download_dir }} copy=no

- name: Install DIGITS
  become: true
  shell: |
    pip install -r requirements.txt
    pip install -e .
    pip uninstall matplotlib
    pip install matplotlib
  args:
    chdir: "{{ download_dir }}/DIGITS-{{ digits_version }}"
    executable: /bin/bash
