---
- name: Install dependencies
  apt: name={{ item }} state=installed update_cache=yes
  become: true
  with_items:
    - build-essential
    - python-dev
    - libbz2-dev
  when: ansible_os_family == "Debian"

- name: Install dependencies
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - python-devel
    - gcc
    - gcc-c++
    - kernel-devel
    - bzip2-devel
  when: ansible_os_family == "RedHat"

- name: Create work directory
  file: path={{ download_dir }} state=directory

- name: Create install directory
  become: true
  file: path={{ boost_prefix }} state=directory
  when: boost_prefix is defined

- name: Get boost source
  get_url: url='http://downloads.sourceforge.net/project/boost/boost/{{ boost_version }}/{{ boost_tar_name  }}' dest={{ download_dir }}

- name: Unpack tarball
  #unarchive: src={{ bvlc_caffe }}{{ caffe_version }}.tar.gz dest={{ download_dir }} copy=no
  command: /bin/tar jxfv {{ download_dir }}/{{ boost_tar_name }} -C {{ download_dir }}

- name: Bootstrap Boost
  command: chdir={{ download_dir }}/{{ boost_build_dir }} ./bootstrap.sh
  when: boost_prefix is not defined

- name: Bootstrap Boost
  command: chdir={{ download_dir }}/{{ boost_build_dir }} ./bootstrap.sh --prefix={{ boost_prefix }}
  when: boost_prefix is defined

- name: Make Boost
  command: chdir={{ download_dir }}/{{ boost_build_dir }} ./b2

- name: Insall Boost
  become: true
  command: chdir={{ download_dir }}/{{ boost_build_dir }} ./b2 install
